In [1]:
import numpy as np
import pandas as pd
import re 
import gensim

In [2]:
data_directory = "../data/"
tables_directory = data_directory + "curated/"
merchants_file_loc = tables_directory + "transactions.parquet"

In [8]:
merchants = pd.read_parquet(merchants_file_loc)
merchants.head()

,user_id,merchant_abn,dollar_value,order_id,order_datetime,merchant_name,tags,sector_tags,revenue_band,take_rate,consumer_name,state,postcode,gender
0,1,28000487688,133.226894,0c37b3f7-c7f1-48cb-bcc7-0a58e76608ea,2021-02-28,Sed Nunc Industries,"((books, periodicals, anD newspapers), (b), (t...","books, periodicals, anD newspapers",b,4.24,Yolanda Williams,WA,6935,Female
1,20864,28000487688,378.937918,f7eca4c5-474b-4ab2-ad61-6a8219b26d67,2021-02-28,Sed Nunc Industries,"((books, periodicals, anD newspapers), (b), (t...","books, periodicals, anD newspapers",b,4.24,Heather Ortiz,QLD,4113,Female
2,22666,28000487688,108.164737,f93ae993-80eb-42d1-aaa6-3659e759ed87,2021-02-28,Sed Nunc Industries,"((books, periodicals, anD newspapers), (b), (t...","books, periodicals, anD newspapers",b,4.24,Melissa Terry,QLD,4055,Female
3,23228,28000487688,329.178020,2a61a2f3-fbca-4011-87a3-6f45b4f1f7ed,2021-02-28,Sed Nunc Industries,"((books, periodicals, anD newspapers), (b), (t...","books, periodicals, anD newspapers",b,4.24,Andrew Casey,NSW,2048,Male
4,5131,28000487688,425.750157,b0b4b456-e286-4b84-8313-f5c7210c7b4b,2021-02-28,Sed Nunc Industries,"((books, periodicals, anD newspapers), (b), (t...","books, periodicals, anD newspapers",b,4.24,Jennifer Hurley,WA,6904,Female

In [9]:
merchants = merchants[["merchant_abn", "sector_tags", "revenue_band", "take_rate"]].drop_duplicates()

In [10]:

def process_tags(tag):
    result = re.search(r'^[\[\(]{2}(.+?(?:, ?.+)*)[\]\)], [\[\(]([a-z])[\]\)], [\(\[].+: (\d+\.?\d+)[\)\]]{2}$', tag)
    return result.group(1), result.group(2), result.group(3)

In [13]:
# merchants[["sector_tags", "revenue_band", "take_rate"]] = merchants.apply(lambda row: process_tags(row.tags), axis='columns', result_type='expand')

In [15]:
np.sort(merchants["sector_tags"].str.lower().str.replace(' +', ' ', regex=True).str.strip().unique())

array(['antique shops - sales, repairs, and restoration services',
       'art dealers and galleries', 'artist supply and craft shops',
       'bicycle shops - sales and service',
       'books, periodicals, and newspapers',
       'cable, satellite, and other pay television and radio services',
       'computer programming , data processing, and integrated systems design services',
       'computers, computer peripheral equipment, and software',
       'digital goods: books, movies, music',
       'equipment, tool, furniture, and appliance rent al and leasing',
       'florists supplies, nursery stock, and flowers',
       'furniture, home furnishings and equipment shops, and manufacturers, except appliances',
       'gift, card, novelty, and souvenir shops',
       'health and beauty spas', 'hobby, toy and game shops',
       'jewelry, watch, clock, and silverware shops',
       'lawn and garden supply outlets, including nurseries',
       'motor vehicle supplies and new parts',
       'music shops - musical instruments, pianos, and sheet music',
       'opticians, optical goods, and eyeglasses', 'shoe shops',
       'stationery, office supplies and printing and writing paper',
       'telecom', 'tent and awning shops',
       'watch, clock, and jewelry repair shops'], dtype=object)